[package]
version = "0.1.0"
name = "veriphoto-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
serde_json = "1.0.133"
sp1-sdk = "3.4.0"
sp1-zkvm = "3.0.0-rc4"
veriphoto-lib = { path = "../lib" }
